name: Build

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        go-version: ['1.23','1.24','1.25']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Go ${{matrix.go-version}}
        uses: actions/setup-go@v4
        with:
          go-version: ${{matrix.go-version}}
      
      - name: Go version
        run: go version
      
      - name: Go test
        run: go test ./...
